name: flutter_test_app
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  bloc: ^2.0.0
  flutter_bloc: ^2.1.1
  flutter:
    sdk: flutter
  provider: ^3.0.0

flutter:
  uses-material-design: true
